name: Maven publish

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        java: [ '11' ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          server-id: ossrh
          server-username: ${{ secrets.MAVEN_USER }}
          server-password: ${{ secrets.MAVEN_PASS }}
      - name: Check env
        run: env
      - name: Check cli
        run: |
          echo "MAVEN_USER is: ${MAVEN_USER}"
          echo "MAVEN_PASS is: ${MAVEN_PASS}"
      - name: Check settings.xml
        run: cat /home/runner/.m2/settings.xml
      - name: Publish to the Maven Central Repository
        run: mvn --batch-mode deploy
